// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volunteer.API.Data;

namespace Volunteer.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201102144600_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 3,
                            Address = "Διεύθυνση Κατοικίας 1, Αθήνα 000 01",
                            FatherName = "Πατρώνυμο1",
                            FirstName = "Όνομα1",
                            LastName = "Επώνυμο1",
                            Phone = "2100000001",
                            Stars = 0
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 4,
                            Address = "Διεύθυνση Κατοικίας 2, Αθήνα 000 02",
                            FatherName = "Πατρώνυμο2",
                            FirstName = "Όνομα2",
                            LastName = "Επώνυμο2",
                            Phone = "2100000002",
                            Stars = 0
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 5,
                            Address = "Διεύθυνση Κατοικίας 3, Αθήνα 000 03",
                            FatherName = "Πατρώνυμο3",
                            FirstName = "Όνομα3",
                            LastName = "Επώνυμο3",
                            Phone = "2100000003",
                            Stars = 0
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 6,
                            Address = "Διεύθυνση Κατοικίας 4, Αθήνα 000 04",
                            FatherName = "Πατρώνυμο4",
                            FirstName = "Όνομα4",
                            LastName = "Επώνυμο4",
                            Phone = "2100000004",
                            Stars = 0
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 7,
                            Address = "Διεύθυνση Κατοικίας 5, Αθήνα 000 05",
                            FatherName = "Πατρώνυμο5",
                            FirstName = "Όνομα5",
                            LastName = "Επώνυμο5",
                            Phone = "2100000005",
                            Stars = 0
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 8,
                            Address = "Διεύθυνση Κατοικίας 6, Αθήνα 000 06",
                            FatherName = "Πατρώνυμο6",
                            FirstName = "Όνομα6",
                            LastName = "Επώνυμο6",
                            Phone = "2100000006",
                            Stars = 0
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 9,
                            Address = "Διεύθυνση Κατοικίας 7, Αθήνα 000 07",
                            FatherName = "Πατρώνυμο7",
                            FirstName = "Όνομα7",
                            LastName = "Επώνυμο7",
                            Phone = "2100000007",
                            Stars = 0
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 10,
                            Address = "Διεύθυνση Κατοικίας 8, Αθήνα 000 08",
                            FatherName = "Πατρώνυμο8",
                            FirstName = "Όνομα8",
                            LastName = "Επώνυμο8",
                            Phone = "2100000008",
                            Stars = 0
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 11,
                            Address = "Διεύθυνση Κατοικίας 9, Αθήνα 000 09",
                            FatherName = "Πατρώνυμο9",
                            FirstName = "Όνομα9",
                            LastName = "Επώνυμο9",
                            Phone = "2100000009",
                            Stars = 0
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 12,
                            Address = "Διεύθυνση Κατοικίας 10, Αθήνα 000 10",
                            FatherName = "Πατρώνυμο10",
                            FirstName = "Όνομα10",
                            LastName = "Επώνυμο10",
                            Phone = "2100000010",
                            Stars = 0
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 13,
                            Address = "Διεύθυνση Κατοικίας 11, Αθήνα 000 11",
                            FatherName = "Πατρώνυμο11",
                            FirstName = "Όνομα11",
                            LastName = "Επώνυμο11",
                            Phone = "2100000011",
                            Stars = 0
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 14,
                            Address = "Διεύθυνση Κατοικίας 12, Αθήνα 000 12",
                            FatherName = "Πατρώνυμο12",
                            FirstName = "Όνομα12",
                            LastName = "Επώνυμο12",
                            Phone = "2100000012",
                            Stars = 0
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 15,
                            Address = "Διεύθυνση Κατοικίας 13, Αθήνα 000 13",
                            FatherName = "Πατρώνυμο13",
                            FirstName = "Όνομα13",
                            LastName = "Επώνυμο13",
                            Phone = "2100000013",
                            Stars = 0
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 16,
                            Address = "Διεύθυνση Κατοικίας 14, Αθήνα 000 14",
                            FatherName = "Πατρώνυμο14",
                            FirstName = "Όνομα14",
                            LastName = "Επώνυμο14",
                            Phone = "2100000014",
                            Stars = 0
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 17,
                            Address = "Διεύθυνση Κατοικίας 15, Αθήνα 000 15",
                            FatherName = "Πατρώνυμο15",
                            FirstName = "Όνομα15",
                            LastName = "Επώνυμο15",
                            Phone = "2100000015",
                            Stars = 0
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 18,
                            Address = "Διεύθυνση Κατοικίας 16, Αθήνα 000 16",
                            FatherName = "Πατρώνυμο16",
                            FirstName = "Όνομα16",
                            LastName = "Επώνυμο16",
                            Phone = "2100000016",
                            Stars = 0
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 19,
                            Address = "Διεύθυνση Κατοικίας 17, Αθήνα 000 17",
                            FatherName = "Πατρώνυμο17",
                            FirstName = "Όνομα17",
                            LastName = "Επώνυμο17",
                            Phone = "2100000017",
                            Stars = 0
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 20,
                            Address = "Διεύθυνση Κατοικίας 18, Αθήνα 000 18",
                            FatherName = "Πατρώνυμο18",
                            FirstName = "Όνομα18",
                            LastName = "Επώνυμο18",
                            Phone = "2100000018",
                            Stars = 0
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 21,
                            Address = "Διεύθυνση Κατοικίας 19, Αθήνα 000 19",
                            FatherName = "Πατρώνυμο19",
                            FirstName = "Όνομα19",
                            LastName = "Επώνυμο19",
                            Phone = "2100000019",
                            Stars = 0
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 22,
                            Address = "Διεύθυνση Κατοικίας 20, Αθήνα 000 20",
                            FatherName = "Πατρώνυμο20",
                            FirstName = "Όνομα20",
                            LastName = "Επώνυμο20",
                            Phone = "2100000020",
                            Stars = 0
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 23,
                            Address = "Διεύθυνση Κατοικίας 21, Αθήνα 000 21",
                            FatherName = "Πατρώνυμο21",
                            FirstName = "Όνομα21",
                            LastName = "Επώνυμο21",
                            Phone = "2100000021",
                            Stars = 0
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 24,
                            Address = "Διεύθυνση Κατοικίας 22, Αθήνα 000 22",
                            FatherName = "Πατρώνυμο22",
                            FirstName = "Όνομα22",
                            LastName = "Επώνυμο22",
                            Phone = "2100000022",
                            Stars = 0
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 25,
                            Address = "Διεύθυνση Κατοικίας 23, Αθήνα 000 23",
                            FatherName = "Πατρώνυμο23",
                            FirstName = "Όνομα23",
                            LastName = "Επώνυμο23",
                            Phone = "2100000023",
                            Stars = 0
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 26,
                            Address = "Διεύθυνση Κατοικίας 24, Αθήνα 000 24",
                            FatherName = "Πατρώνυμο24",
                            FirstName = "Όνομα24",
                            LastName = "Επώνυμο24",
                            Phone = "2100000024",
                            Stars = 0
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 27,
                            Address = "Διεύθυνση Κατοικίας 25, Αθήνα 000 25",
                            FatherName = "Πατρώνυμο25",
                            FirstName = "Όνομα25",
                            LastName = "Επώνυμο25",
                            Phone = "2100000025",
                            Stars = 0
                        },
                        new
                        {
                            Id = 26,
                            AccountId = 28,
                            Address = "Διεύθυνση Κατοικίας 26, Αθήνα 000 26",
                            FatherName = "Πατρώνυμο26",
                            FirstName = "Όνομα26",
                            LastName = "Επώνυμο26",
                            Phone = "2100000026",
                            Stars = 0
                        },
                        new
                        {
                            Id = 27,
                            AccountId = 29,
                            Address = "Διεύθυνση Κατοικίας 27, Αθήνα 000 27",
                            FatherName = "Πατρώνυμο27",
                            FirstName = "Όνομα27",
                            LastName = "Επώνυμο27",
                            Phone = "2100000027",
                            Stars = 0
                        },
                        new
                        {
                            Id = 28,
                            AccountId = 30,
                            Address = "Διεύθυνση Κατοικίας 28, Αθήνα 000 28",
                            FatherName = "Πατρώνυμο28",
                            FirstName = "Όνομα28",
                            LastName = "Επώνυμο28",
                            Phone = "2100000028",
                            Stars = 0
                        },
                        new
                        {
                            Id = 29,
                            AccountId = 31,
                            Address = "Διεύθυνση Κατοικίας 29, Αθήνα 000 29",
                            FatherName = "Πατρώνυμο29",
                            FirstName = "Όνομα29",
                            LastName = "Επώνυμο29",
                            Phone = "2100000029",
                            Stars = 0
                        },
                        new
                        {
                            Id = 30,
                            AccountId = 32,
                            Address = "Διεύθυνση Κατοικίας 30, Αθήνα 000 30",
                            FatherName = "Πατρώνυμο30",
                            FirstName = "Όνομα30",
                            LastName = "Επώνυμο30",
                            Phone = "2100000030",
                            Stars = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
