// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University.API.Data;

namespace University.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201026190323_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "pch",
                            Email = "pch@uniwa.gr",
                            FacultyId = 1,
                            Name = "Τμήμα Δημόσιας και Κοινοτικής Υγείας",
                            Phone = "+302132010221",
                            Website = "http://pch.uniwa.gr/"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "php",
                            Email = "php@uniwa.gr",
                            FacultyId = 1,
                            Name = "Τμήμα Πολιτικών Δημόσιας Υγείας",
                            Phone = "+302132010207",
                            Website = "http://php.uniwa.gr/"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "ecec",
                            Email = "ecec@uniwa.gr",
                            FacultyId = 2,
                            Name = "Τμήμα Αγωγής και Φροντίδας στην Πρώιμη Παιδική Ηλικία",
                            Phone = "+302105387092",
                            Website = "http://ecec.uniwa.gr/"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "alis",
                            Email = "alis@uniwa.gr",
                            FacultyId = 2,
                            Name = "Τμήμα Αρχειονομίας, Βιβλιοθηκονομίας και Συστημάτων Πληροφόρησης",
                            Phone = "+302105385203",
                            Website = "http://alis.uniwa.gr/"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "ba",
                            Email = "ba@uniwa.gr",
                            FacultyId = 2,
                            Name = "Τμήμα Διοίκησης Επιχειρήσεων",
                            Phone = "+302105381151",
                            Website = "http://ba.uniwa.gr/"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "tourism",
                            Email = "tourism@uniwa.gr",
                            FacultyId = 2,
                            Name = "Τμήμα Διοίκησης Τουρισμού",
                            Phone = "+302105385211",
                            Website = "http://tourism.uniwa.gr/"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "sw",
                            Email = "sw@uniwa.gr",
                            FacultyId = 2,
                            Name = "Τμήμα Κοινωνικής Εργασίας",
                            Phone = "+302105381173",
                            Website = "http://sw.uniwa.gr/"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "accfin",
                            Email = "accfin@uniwa.gr",
                            FacultyId = 2,
                            Name = "Τμήμα Λογιστικής και Χρηματοοικονομικής",
                            Phone = "+302105381125",
                            Website = "http://accfin.uniwa.gr/"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "fst",
                            Email = "fst@uniwa.gr",
                            FacultyId = 3,
                            Name = "Τμήμα Επιστήμης και Τεχνολογίας Τροφίμων",
                            Phone = "+302105385506",
                            Website = "http://fst.uniwa.gr/"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "wvbs",
                            Email = "wvbs@uniwa.gr",
                            FacultyId = 3,
                            Name = "Τμήμα Επιστημών Οίνου, Αμπέλου και Ποτών",
                            Phone = "+302105385538",
                            Website = "http://wvbs.uniwa.gr/"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "bisc",
                            Email = "bisc@uniwa.gr",
                            FacultyId = 4,
                            Name = "Τμήμα Βιοϊατρικών Επιστημών",
                            Phone = "+302105385690",
                            Website = "http://bisc.uniwa.gr/"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "ot",
                            Email = "ot@uniwa.gr",
                            FacultyId = 4,
                            Name = "Τμήμα Εργοθεραπείας",
                            Phone = "+302105387456",
                            Website = "http://ot.uniwa.gr/"
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "midw",
                            Email = "midw@uniwa.gr",
                            FacultyId = 4,
                            Name = "Τμήμα Μαιευτικής",
                            Phone = "+302105387481",
                            Website = "http://midw.uniwa.gr/"
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "nurs",
                            Email = "nurs@uniwa.gr",
                            FacultyId = 4,
                            Name = "Τμήμα Νοσηλευτικής",
                            Phone = "+302105385616",
                            Website = "http://nurs.uniwa.gr/"
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "phys",
                            Email = "phys@uniwa.gr",
                            FacultyId = 4,
                            Name = "Τμήμα Φυσικοθεραπείας",
                            Phone = "+302105387485",
                            Website = "http://phys.uniwa.gr/"
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "gd",
                            Email = "gd@uniwa.gr",
                            FacultyId = 5,
                            Name = "Τμήμα Γραφιστικής και Οπτικής Επικοινωνίας",
                            Phone = "+302105385466",
                            Website = "http://gd.uniwa.gr/"
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "ia",
                            Email = "decor@teiath.gr",
                            FacultyId = 5,
                            Name = "Τμήμα Εσωτερικής Αρχιτεκτονικής",
                            Phone = "+302105385405",
                            Website = "http://ia.uniwa.gr/"
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "cons",
                            Email = "cons@uniwa.gr",
                            FacultyId = 5,
                            Name = "Τμήμα Συντήρησης Αρχαιοτήτων και Έργων Τέχνης",
                            Phone = "+302105385462",
                            Website = "http://cons.uniwa.gr/"
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "phaa",
                            Email = "phaa@uniwa.gr",
                            FacultyId = 5,
                            Name = "Τμήμα Φωτογραφίας και Οπτικοακουστικών Τεχνών",
                            Phone = "+302105385411",
                            Website = "http://phaa.uniwa.gr/"
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "eee",
                            Email = "eee@uniwa.gr",
                            FacultyId = 6,
                            Name = "Τμήμα Ηλεκτρολόγων και Ηλεκτρονικών Μηχανικών",
                            Phone = "+302105381225",
                            Website = "http://eee.uniwa.gr/"
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "bme",
                            Email = "bme@uniwa.gr",
                            FacultyId = 6,
                            Name = "Τμήμα Μηχανικών Βιοϊατρικής",
                            Phone = "+302105385303",
                            Website = "http://bme.uniwa.gr/"
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "idpe",
                            Email = "idpe@uniwa.gr",
                            FacultyId = 6,
                            Name = "Τμήματος Μηχανικών Βιομηχανικής Σχεδίασης και Παραγωγής",
                            Phone = "+302105381219",
                            Website = "http://idpe.uniwa.gr/"
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "ice",
                            Email = "ice@uniwa.gr",
                            FacultyId = 6,
                            Name = "Τμήμα Μηχανικών Πληροφορικής και Υπολογιστών",
                            Phone = "+302105385382",
                            Website = "http://ice.uniwa.gr/"
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "geo",
                            Email = "geo@uniwa.gr",
                            FacultyId = 6,
                            Name = "Τμήμα Μηχανικών Τοπογραφίας και Γεωπληροφορικής",
                            Phone = "+302105385854",
                            Website = "http://geo.uniwa.gr/"
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "mech",
                            Email = "mech@uniwa.gr",
                            FacultyId = 6,
                            Name = "Τμήμα Μηχανολόγων Μηχανικών",
                            Phone = "+302105381506",
                            Website = "http://mech.uniwa.gr/"
                        },
                        new
                        {
                            Id = 26,
                            Abbreviation = "na",
                            Email = "na@uniwa.gr",
                            FacultyId = 6,
                            Name = "Τμήμα Ναυπηγών Μηχανικών",
                            Phone = "+302105385310",
                            Website = "http://na.uniwa.gr/"
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "civ",
                            Email = "civ@uniwa.gr",
                            FacultyId = 6,
                            Name = "Τμήμα Πολιτικών Μηχανικών",
                            Phone = "+302105381215",
                            Website = "http://civ.uniwa.gr/"
                        },
                        new
                        {
                            Id = 28,
                            Abbreviation = "ode",
                            Email = "ode@aueb.gr",
                            FacultyId = 7,
                            Name = "Τμήμα Οργάνωσης και Διοίκησης Επιχειρήσεων",
                            Phone = "+302108203308",
                            Website = "https://www.dept.aueb.gr/ode"
                        },
                        new
                        {
                            Id = 29,
                            Abbreviation = "mbv",
                            Email = "secretary.marketing@aueb.gr",
                            FacultyId = 7,
                            Name = "Τμήμα Μάρκετινγκ και Επικοινωνίας",
                            Phone = "+302108203101",
                            Website = "https://www.dept.aueb.gr/mbc"
                        },
                        new
                        {
                            Id = 30,
                            Abbreviation = "loxri",
                            Email = "accfin@aueb.gr",
                            FacultyId = 7,
                            Name = "Τμήμα Λογιστικής και Χρηματοοικονομικής",
                            Phone = "+302108203300",
                            Website = "https://www.dept.aueb.gr/loxri"
                        },
                        new
                        {
                            Id = 31,
                            Abbreviation = "dmst",
                            Email = "dmst@aueb.gr",
                            FacultyId = 7,
                            Name = "Τμήμα Διοικητικής Επιστήμης και Τεχνολογίας",
                            Phone = "+302108203129",
                            Website = "https://www.dept.aueb.gr/dmst"
                        },
                        new
                        {
                            Id = 32,
                            Abbreviation = "econ",
                            Email = "econ@aueb.gr",
                            FacultyId = 8,
                            Name = "Τμήμα Οικονομικής Επιστήμης",
                            Phone = "+302108203303",
                            Website = "https://www.dept.aueb.gr/econ"
                        },
                        new
                        {
                            Id = 33,
                            Abbreviation = "deos",
                            Email = "deossecr@aueb.gr",
                            FacultyId = 8,
                            Name = "Τμήμα Διεθνών και Ευρωπαϊκών Οικονομικών Σπουδών",
                            Phone = "+302108203106",
                            Website = "https://www.dept.aueb.gr/deos"
                        },
                        new
                        {
                            Id = 34,
                            Abbreviation = "cs",
                            Email = "infotech@aueb.gr",
                            FacultyId = 9,
                            Name = "Τμήμα Πληροφορικής",
                            Phone = "+302108203315",
                            Website = "https://www.dept.aueb.gr/cs"
                        },
                        new
                        {
                            Id = 35,
                            Abbreviation = "stat",
                            Email = "stat@aueb.gr",
                            FacultyId = 9,
                            Name = "Τμήμα Στατιστικής",
                            Phone = "+302108203112",
                            Website = "https://www.dept.aueb.gr/stat"
                        });
                });

            modelBuilder.Entity("Model.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "sph",
                            Email = "sph@uniwa.gr",
                            Name = "Σχολή Δημόσιας Υγείας",
                            Phone = "+302132010115",
                            UniversityId = 1,
                            Website = "https://www.uniwa.gr/spoydes/scholes-kai-tmimata/sph/"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "sdo",
                            Email = "sdoke@uniwa.gr",
                            Name = "Σχολή Διοικητικών, Οικονομικών & Κοινωνικών Επιστημών",
                            Phone = "",
                            UniversityId = 1,
                            Website = "https://www.uniwa.gr/spoydes/scholes-kai-tmimata/sdo/"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "ffs",
                            Email = "ffs@uniwa.gr",
                            Name = "Σχολή Επιστημών Τροφίμων",
                            Phone = "2105385501",
                            UniversityId = 1,
                            Website = "https://www.uniwa.gr/spoydes/scholes-kai-tmimata/ffs/"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "seyp",
                            Email = "seyp@uniwa.gr",
                            Name = "Σχολή Επιστημών Υγείας και Πρόνοιας",
                            Phone = "2105385601",
                            UniversityId = 1,
                            Website = "https://www.uniwa.gr/spoydes/scholes-kai-tmimata/seyp/"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "aac",
                            Email = "setp@uniwa.gr",
                            Name = "Σχολή Εφαρμοσμένων Τεχνών και Πολιτισμού",
                            Phone = "2105385401",
                            UniversityId = 1,
                            Website = "https://www.uniwa.gr/spoydes/scholes-kai-tmimata/aac/"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "feng",
                            Email = "feng@uniwa.gr",
                            Name = "Σχολή Μηχανικών",
                            Phone = "+302105381212",
                            UniversityId = 1,
                            Website = "https://www.uniwa.gr/spoydes/scholes-kai-tmimata/feng/"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "sde",
                            Email = "sde@aueb.gr",
                            Name = "Σχολή Διοίκησης Επιχειρήσεων",
                            Phone = "+302108214510",
                            UniversityId = 2,
                            Website = "https://www.dept.aueb.gr/el/school_of_business"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "soe",
                            Email = "secr_soe@aueb.gr",
                            Name = "Σχολή Οικονομικών Επιστημών",
                            Phone = "+302108203416",
                            UniversityId = 2,
                            Website = "https://www.dept.aueb.gr/el/school_of_economics"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "soi",
                            Email = "webmaster@aueb.gr",
                            Name = "Σχολή Επιστημών και Τεχνολογίας της Πληροφορίας",
                            Phone = "+302108203911",
                            UniversityId = 2,
                            Website = "https://www.dept.aueb.gr/el/school_of_informatics"
                        });
                });

            modelBuilder.Entity("Model.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "uniwa",
                            AccountId = 1,
                            Address = "Αγίου Σπυρίδωνος 28, Αιγάλεω 122 43",
                            Name = "Πανεπιστήμιο Δυτικής Αττικής",
                            Phone = "+302105385100",
                            Website = "https://www.uniwa.gr"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "aueb",
                            AccountId = 2,
                            Address = "Πατησίων 76, Αθήνα 104 34",
                            Name = "Οικονομικό Πανεπιστήμιο Αθηνών",
                            Phone = "+302108203911",
                            Website = "https://www.aueb.gr"
                        });
                });

            modelBuilder.Entity("Model.Department", b =>
                {
                    b.HasOne("Model.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Faculty", b =>
                {
                    b.HasOne("Model.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
